ccflags-y := -O3 -mcpu=cortex-a9 -mtune=cortex-a9 -marm -mfpu=neon -mvectorize-with-neon-quad -munaligned-access -ffast-math -floop-block -floop-interchange -floop-nest-optimize -floop-parallelize-all -floop-strip-mine
obj-y += tegra_ion.o
